# CI jobs

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  # schedule:
  #   # Weekly build
  #   - cron: '15 15 * * 0'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5
        with:
          submodules: true

      # 1. WiFi 스트리머 예제만 빌드
      - name: build wifi-img-streamer example
        run: docker run --rm -v ${PWD}:/module bitcraze/aideck tools/build/make-example examples/other/wifi-img-streamer build image

      # 2. 결과물 복사 (경로 주의!)
      - name: rename bin file
        run: cp examples/other/wifi-img-streamer/BUILD/GAP8_V2/GCC_RISCV_FREERTOS/target.board.devices.flash.img aideck_gap8.bin

      # 3. 업로드
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v7
        with:
          name: wifi-streamer-firmware
          path: aideck_gap8.bin
